import type { Metadata } from "next";

import { generatePageMetadata } from "@/lib/metadata";
import { breadcrumbSchema } from "@/lib/schema";
import { siteConfig } from "@/lib/site.config";

import StructuredData from "@/components/seo/StructuredData";
import LegalPage, { type LegalSection } from "@/components/shared/LegalPage";

export const metadata: Metadata = generatePageMetadata({
  title: "Privacy Policy",
  description:
    "How Engage Commercial Fitouts collects, uses and protects personal information provided through this website and project enquiries.",
  path: "/privacy-policy",
});

// TODO(launch): have this policy reviewed against the confirmed company
// registration details and applicable data-protection requirements before
// the site goes live. Placeholder company details live in site.config.ts.
const SECTIONS: LegalSection[] = [
  {
    heading: "1. Who we are",
    paragraphs: [
      `This website is operated by ${siteConfig.legal.registeredName} ("Engage", "we", "us"). Engage provides commercial fit-out, renovation and project delivery services in ${siteConfig.address.locality}, ${siteConfig.address.countryName}.`,
      "Questions about this policy or about how your information is handled can be sent to us using the contact page.",
    ],
  },
  {
    heading: "2. Information we collect",
    paragraphs: [
      "We collect information you choose to provide when you contact us or submit a project enquiry. This may include:",
    ],
    bullets: [
      "Your name and company name",
      "Contact details such as email address and phone number",
      "Information about your property or project, including location, size, condition, objectives, timelines and budget expectations",
      "Files you choose to upload, such as plans, photographs or briefs",
      "Basic technical information generated by your visit, such as browser type and pages viewed",
    ],
  },
  {
    heading: "3. How we use your information",
    bullets: [
      "To respond to your enquiry and arrange the appropriate next step",
      "To assess, scope and prepare proposals for your project",
      "To communicate with you during a project",
      "To meet legal, regulatory or contractual obligations",
      "To maintain and improve this website",
    ],
  },
  {
    heading: "4. Legal basis and consent",
    paragraphs: [
      "We process enquiry information because you have asked us to respond to you, and because processing is necessary to take steps towards providing our services. Where we rely on your consent — for example, when you submit the enquiry form — you may withdraw it at any time by contacting us.",
    ],
  },
  {
    heading: "5. Sharing your information",
    paragraphs: [
      "We do not sell personal information. We may share information with service providers who support the operation of this website or the delivery of our services (for example, hosting or email providers), and where required by law. Any providers acting on our behalf are required to protect your information.",
    ],
  },
  {
    heading: "6. Data retention",
    paragraphs: [
      "We keep enquiry and project information for as long as needed to handle your enquiry, deliver any resulting project and meet legal or contractual obligations, after which it is deleted or anonymised.",
    ],
  },
  {
    heading: "7. Security",
    paragraphs: [
      "We apply appropriate technical and organisational measures to protect the information you provide. No method of transmission or storage is completely secure, but we take reasonable steps to safeguard your data.",
    ],
  },
  {
    heading: "8. Your rights",
    paragraphs: [
      "Subject to applicable law, you may request access to, correction of, or deletion of the personal information we hold about you, and you may object to or ask us to restrict certain processing. To exercise these rights, contact us through the contact page.",
    ],
  },
  {
    heading: "9. Cookies",
    paragraphs: [
      "For information about the cookies used on this website, please see our Cookie Policy.",
    ],
  },
  {
    heading: "10. Changes to this policy",
    paragraphs: [
      "We may update this policy from time to time. The latest version will always be published on this page.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <>
      <StructuredData
        data={breadcrumbSchema([
          { name: "Home", url: "/" },
          { name: "Privacy Policy", url: "/privacy-policy" },
        ])}
      />
      <LegalPage
        title="Privacy Policy"
        breadcrumbLabel="Privacy Policy"
        intro="How Engage Commercial Fitouts collects, uses and protects the personal information provided through this website."
        sections={SECTIONS}
      />
    </>
  );
}
